# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_processing_system7_0_1/arty_processing_system7_0_1.xci
# IP: The module: 'arty_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_processing_system7_0_1/arty_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: Z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_processing_system7_0_1/arty_processing_system7_0_1.xci
# IP: The module: 'arty_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_processing_system7_0_1/arty_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
