# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/20170720_arty/Arty/Vivado/arty/arty.srcs/sources_1/bd/arty/ip/arty_proc_sys_reset_2_0/arty_proc_sys_reset_2_0.xci
# IP: The module: 'arty_proc_sys_reset_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/20170720_arty/Arty/Vivado/arty/arty.srcs/sources_1/bd/arty/ip/arty_proc_sys_reset_2_0/arty_proc_sys_reset_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_proc_sys_reset_2_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/20170720_arty/Arty/Vivado/arty/arty.srcs/sources_1/bd/arty/ip/arty_proc_sys_reset_2_0/arty_proc_sys_reset_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_proc_sys_reset_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/20170720_arty/Arty/Vivado/arty/arty.srcs/sources_1/bd/arty/ip/arty_proc_sys_reset_2_0/arty_proc_sys_reset_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_proc_sys_reset_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: z:/20170720_arty/Arty/Vivado/arty/arty.srcs/sources_1/bd/arty/ip/arty_proc_sys_reset_2_0/arty_proc_sys_reset_2_0.xci
# IP: The module: 'arty_proc_sys_reset_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/20170720_arty/Arty/Vivado/arty/arty.srcs/sources_1/bd/arty/ip/arty_proc_sys_reset_2_0/arty_proc_sys_reset_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_proc_sys_reset_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/20170720_arty/Arty/Vivado/arty/arty.srcs/sources_1/bd/arty/ip/arty_proc_sys_reset_2_0/arty_proc_sys_reset_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_proc_sys_reset_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/20170720_arty/Arty/Vivado/arty/arty.srcs/sources_1/bd/arty/ip/arty_proc_sys_reset_2_0/arty_proc_sys_reset_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_proc_sys_reset_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
