# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir Z:/20170720_arty/Arty/Vivado/arty_uart1/arty.cache/wt [current_project]
set_property parent.project_path Z:/20170720_arty/Arty/Vivado/arty_uart1/arty.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-z7-20:part0:1.0 [current_project]
set_property ip_output_repo z:/20170720_arty/Arty/Vivado/arty_uart1/arty.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib Z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/hdl/arty_wrapper.v
add_files Z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/arty.bd
set_property used_in_implementation false [get_files -all z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_proc_sys_reset_0_0/arty_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_proc_sys_reset_0_0/arty_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_proc_sys_reset_0_0/arty_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_proc_sys_reset_1_0/arty_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_proc_sys_reset_1_0/arty_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_proc_sys_reset_1_0/arty_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_processing_system7_0_1/arty_processing_system7_0_1.xdc]
set_property used_in_implementation false [get_files -all z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_axi_gpio_0_0/arty_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_axi_gpio_0_0/arty_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_axi_gpio_0_0/arty_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_axi_gpio_0_1/arty_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_axi_gpio_0_1/arty_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_axi_gpio_0_1/arty_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_proc_sys_reset_2_0/arty_proc_sys_reset_2_0_board.xdc]
set_property used_in_implementation false [get_files -all z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_proc_sys_reset_2_0/arty_proc_sys_reset_2_0.xdc]
set_property used_in_implementation false [get_files -all z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_proc_sys_reset_2_0/arty_proc_sys_reset_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_xbar_0/arty_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_auto_pc_0/arty_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all Z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/arty_ooc.xdc]
set_property is_locked true [get_files Z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/arty.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top arty_wrapper -part xc7z020clg400-1


write_checkpoint -force -noxdef arty_wrapper.dcp

catch { report_utilization -file arty_wrapper_utilization_synth.rpt -pb arty_wrapper_utilization_synth.pb }
