# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/arty/arty.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty || ORIG_REF_NAME==arty}]

# IP: bd/arty/ip/arty_proc_sys_reset_0_0/arty_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_proc_sys_reset_0_0 || ORIG_REF_NAME==arty_proc_sys_reset_0_0}]

# IP: bd/arty/ip/arty_proc_sys_reset_1_0/arty_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_proc_sys_reset_1_0 || ORIG_REF_NAME==arty_proc_sys_reset_1_0}]

# IP: bd/arty/ip/arty_xlconcat_0_0/arty_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_xlconcat_0_0 || ORIG_REF_NAME==arty_xlconcat_0_0}]

# IP: bd/arty/ip/arty_processing_system7_0_1/arty_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_processing_system7_0_1 || ORIG_REF_NAME==arty_processing_system7_0_1}]

# IP: bd/arty/ip/arty_axi_gpio_0_0/arty_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_axi_gpio_0_0 || ORIG_REF_NAME==arty_axi_gpio_0_0}]

# IP: bd/arty/ip/arty_axi_gpio_0_1/arty_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_axi_gpio_0_1 || ORIG_REF_NAME==arty_axi_gpio_0_1}]

# IP: bd/arty/ip/arty_proc_sys_reset_2_0/arty_proc_sys_reset_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_proc_sys_reset_2_0 || ORIG_REF_NAME==arty_proc_sys_reset_2_0}]

# IP: bd/arty/ip/arty_ps7_axi_periph_0/arty_ps7_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_ps7_axi_periph_0 || ORIG_REF_NAME==arty_ps7_axi_periph_0}]

# IP: bd/arty/ip/arty_xbar_0/arty_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_xbar_0 || ORIG_REF_NAME==arty_xbar_0}]

# IP: bd/arty/ip/arty_auto_pc_0/arty_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arty_auto_pc_0 || ORIG_REF_NAME==arty_auto_pc_0}]

# XDC: bd/arty/arty_ooc.xdc
