# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/20170720_arty/Arty/Vivado/arty/arty.srcs/sources_1/bd/arty/ip/arty_axi_gpio_0_1/arty_axi_gpio_0_1.xci
# IP: The module: 'arty_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/20170720_arty/Arty/Vivado/arty/arty.srcs/sources_1/bd/arty/ip/arty_axi_gpio_0_1/arty_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/20170720_arty/Arty/Vivado/arty/arty.srcs/sources_1/bd/arty/ip/arty_axi_gpio_0_1/arty_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/20170720_arty/Arty/Vivado/arty/arty.srcs/sources_1/bd/arty/ip/arty_axi_gpio_0_1/arty_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: z:/20170720_arty/Arty/Vivado/arty/arty.srcs/sources_1/bd/arty/ip/arty_axi_gpio_0_1/arty_axi_gpio_0_1.xci
# IP: The module: 'arty_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/20170720_arty/Arty/Vivado/arty/arty.srcs/sources_1/bd/arty/ip/arty_axi_gpio_0_1/arty_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/20170720_arty/Arty/Vivado/arty/arty.srcs/sources_1/bd/arty/ip/arty_axi_gpio_0_1/arty_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/20170720_arty/Arty/Vivado/arty/arty.srcs/sources_1/bd/arty/ip/arty_axi_gpio_0_1/arty_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
