# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_xbar_0/arty_xbar_0.xci
# IP: The module: 'arty_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_xbar_0/arty_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: Z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_xbar_0/arty_xbar_0.xci
# IP: The module: 'arty_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/20170720_arty/Arty/Vivado/arty_uart1/arty.srcs/sources_1/bd/arty/ip/arty_xbar_0/arty_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arty_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
